"""
Embedding Retriever - Retrieves embeddings from S3 output location.

This module provides functionality to download and parse embedding files
generated by Bedrock async invocations from S3. Supports streaming JSON
parsing for large files to reduce memory footprint.
"""

import json
import logging
from typing import List, Dict, Any, Optional
from io import BytesIO
import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

# Try to import ijson for streaming JSON parsing
try:
    import ijson
    IJSON_AVAILABLE = True
except ImportError:
    IJSON_AVAILABLE = False
    logger.warning(
        "ijson not available - large file optimization disabled. "
        "Install with: pip install ijson"
    )


class EmbeddingData:
    """Model representing a single embedding with metadata.

    Attributes:
        embedding: The embedding vector (list of floats)
        embedding_option: List of embedding types (visual, audio, transcription)
        embedding_scope: Scope of the embedding (clip, asset)
        start_sec: Start time in seconds
        end_sec: End time in seconds
    """

    def __init__(
        self,
        embedding: List[float],
        embedding_option: List[str],
        embedding_scope: str,
        start_sec: float,
        end_sec: float,
    ):
        self.embedding = embedding
        self.embedding_option = embedding_option
        self.embedding_scope = embedding_scope
        self.start_sec = start_sec
        self.end_sec = end_sec

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "embedding": self.embedding,
            "embeddingOption": self.embedding_option,
            "embeddingScope": self.embedding_scope,
            "startSec": self.start_sec,
            "endSec": self.end_sec,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "EmbeddingData":
        """Create EmbeddingData from dictionary.

        Extracts embedding vector and metadata including:
        - embeddingOption: List of embedding types (visual, audio, transcription)
        - embeddingScope: Scope of the embedding (clip, asset)
        - startSec: Start timecode in seconds
        - endSec: End timecode in seconds

        Args:
            data: Dictionary containing embedding data

        Returns:
            EmbeddingData instance with extracted metadata
        """
        # Convert Decimal to float for timecodes (boto3 returns Decimals from AWS responses)
        start_sec = data.get("startSec", 0.0)
        end_sec = data.get("endSec", 0.0)
        
        return cls(
            embedding=data["embedding"],
            embedding_option=data.get("embeddingOption", []),
            embedding_scope=data.get("embeddingScope", "clip"),
            start_sec=float(start_sec) if start_sec is not None else 0.0,
            end_sec=float(end_sec) if end_sec is not None else 0.0,
        )

    def get_metadata(self) -> Dict[str, Any]:
        """Extract metadata from embedding data.

        Returns a dictionary containing all metadata fields without the
        embedding vector itself. Useful for logging, storage, and search.

        Returns:
            Dictionary with metadata fields:
            - embedding_option: List of embedding types
            - embedding_scope: Scope of the embedding
            - start_timecode: Start time in seconds
            - end_timecode: End time in seconds
        """
        return {
            "embedding_option": self.embedding_option,
            "embedding_scope": self.embedding_scope,
            "start_timecode": self.start_sec,
            "end_timecode": self.end_sec,
        }


class EmbeddingRetriever:
    """
    Retrieves and parses embeddings from S3 output location.

    Downloads embedding files from S3 and parses them into structured
    EmbeddingData objects for further processing.
    """

    def __init__(self, s3_client: Optional[boto3.client] = None, use_streaming: bool = True):
        """
        Initialize the embedding retriever.

        Args:
            s3_client: Optional boto3 S3 client. If not provided, creates a new one.
            use_streaming: Enable streaming JSON parsing for large files (default: True)
                          Requires ijson library. Falls back to standard parsing if unavailable.
        """
        self.s3_client = s3_client or boto3.client("s3")
        self.use_streaming = use_streaming and IJSON_AVAILABLE
        
        if use_streaming and not IJSON_AVAILABLE:
            logger.warning(
                "Streaming JSON parsing requested but ijson not available. "
                "Using standard parsing instead."
            )

    def retrieve_embeddings(self, s3_uri: str) -> List[EmbeddingData]:
        """
        Retrieve embeddings from S3 output location.

        Downloads the embedding file from S3 and parses it into a list
        of EmbeddingData objects.

        Args:
            s3_uri: S3 URI of the embedding output file (s3://bucket/key)

        Returns:
            List of EmbeddingData objects

        Raises:
            ValueError: If S3 URI is invalid or file format is incorrect
            ClientError: If S3 download fails
        """
        logger.info(f"Retrieving embeddings from {s3_uri}")

        # Parse S3 URI
        bucket, key = self._parse_s3_uri(s3_uri)

        # Download file from S3
        embedding_data = self._download_from_s3(bucket, key)

        # Parse embeddings
        embeddings = self._parse_embeddings(embedding_data)

        logger.info(f"Retrieved {len(embeddings)} embeddings from {s3_uri}")
        return embeddings

    def _parse_s3_uri(self, s3_uri: str) -> tuple[str, str]:
        """
        Parse S3 URI into bucket and key.

        Args:
            s3_uri: S3 URI in format s3://bucket/key

        Returns:
            Tuple of (bucket, key)

        Raises:
            ValueError: If URI format is invalid
        """
        if not s3_uri.startswith("s3://"):
            raise ValueError(f"Invalid S3 URI format: {s3_uri}. Must start with s3://")

        # Remove s3:// prefix
        path = s3_uri[5:]

        # Split into bucket and key
        parts = path.split("/", 1)
        if len(parts) != 2:
            raise ValueError(
                f"Invalid S3 URI format: {s3_uri}. Must be s3://bucket/key"
            )

        bucket, key = parts
        return bucket, key

    def _download_from_s3(self, bucket: str, key: str) -> bytes:
        """
        Download file from S3 with streaming.

        Uses streaming to efficiently handle large files without loading
        the entire file into memory at once.

        Args:
            bucket: S3 bucket name
            key: S3 object key

        Returns:
            File contents as bytes

        Raises:
            ClientError: If download fails
        """
        try:
            logger.debug(f"Downloading s3://{bucket}/{key} with streaming")
            response = self.s3_client.get_object(Bucket=bucket, Key=key)

            # Stream the file in chunks to handle large files efficiently
            body = response["Body"]
            chunks = []
            chunk_size = 1024 * 1024  # 1MB chunks
            total_bytes = 0

            for chunk in body.iter_chunks(chunk_size=chunk_size):
                chunks.append(chunk)
                total_bytes += len(chunk)

            data = b"".join(chunks)
            logger.debug(f"Downloaded {total_bytes} bytes from S3 using streaming")
            return data
        except ClientError as e:
            error_code = e.response.get("Error", {}).get("Code", "Unknown")
            logger.error(f"Failed to download from S3: {error_code} - {str(e)}")
            raise

    def _parse_embeddings(self, data: bytes) -> List[EmbeddingData]:
        """
        Parse embedding data from JSON or JSONL format.

        Supports both JSON format (single object with embeddings array)
        and JSONL format (one embedding per line). For large files (>1MB),
        uses streaming JSON parsing if available to reduce memory footprint.

        Args:
            data: Raw file contents as bytes

        Returns:
            List of EmbeddingData objects

        Raises:
            ValueError: If data format is invalid
        """
        try:
            # For large files, use streaming parser if available
            if self.use_streaming and len(data) > 1024 * 1024:  # > 1MB
                logger.debug(
                    f"Using streaming JSON parser for large file ({len(data)} bytes)"
                )
                return self._parse_json_streaming(data)
            
            # For smaller files, use standard parsing
            content = data.decode("utf-8")

            # Check if it's JSONL (multiple lines with JSON objects)
            if "\n" in content.strip() and not content.strip().startswith("{"):
                return self._parse_jsonl(content)

            # Parse as single JSON object
            return self._parse_json(content)

        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            logger.error(f"Failed to parse embedding data: {str(e)}")
            raise ValueError(f"Invalid embedding data format: {str(e)}")

    def _parse_json(self, content: str) -> List[EmbeddingData]:
        """
        Parse JSON format embedding data.

        Supports both Marengo 3.0 format and legacy format:

        Marengo 3.0 format (single embedding):
        {
            "data": {
                "embedding": [float, ...],
                "embeddingOption": ["visual", "audio"],
                "embeddingScope": "clip",
                "startSec": 0.0,
                "endSec": 6.0
            }
        }

        Marengo 3.0 format (multiple embeddings):
        {
            "data": [
                {
                    "embedding": [float, ...],
                    "embeddingOption": ["visual", "audio"],
                    "embeddingScope": "clip",
                    "startSec": 0.0,
                    "endSec": 6.0
                },
                ...
            ]
        }

        Legacy format:
        {
            "embeddings": [
                {
                    "embedding": [float, ...],
                    "embeddingOption": ["visual", "audio"],
                    "embeddingScope": "clip",
                    "startSec": 0.0,
                    "endSec": 6.0
                }
            ]
        }

        Args:
            content: JSON string content

        Returns:
            List of EmbeddingData objects

        Raises:
            ValueError: If format is invalid
        """
        data = json.loads(content)

        # Check for Marengo 3.0 format (data field)
        if "data" in data:
            data_field = data["data"]

            # Handle single embedding (data is an object)
            if isinstance(data_field, dict):
                try:
                    return [EmbeddingData.from_dict(data_field)]
                except (KeyError, TypeError) as e:
                    raise ValueError(f"Invalid Marengo 3.0 embedding format: {str(e)}")

            # Handle multiple embeddings (data is a list)
            elif isinstance(data_field, list):
                embeddings = []
                for idx, emb_data in enumerate(data_field):
                    try:
                        embeddings.append(EmbeddingData.from_dict(emb_data))
                    except (KeyError, TypeError) as e:
                        logger.warning(
                            f"Skipping invalid embedding at index {idx}: {str(e)}"
                        )
                        continue
                return embeddings
            else:
                raise ValueError(
                    f"'data' field must be an object or array, got {type(data_field)}"
                )

        # Check for legacy format (embeddings field)
        elif "embeddings" in data:
            embeddings_list = data["embeddings"]
            if not isinstance(embeddings_list, list):
                raise ValueError("'embeddings' field must be an array")

            embeddings = []
            for idx, emb_data in enumerate(embeddings_list):
                try:
                    embeddings.append(EmbeddingData.from_dict(emb_data))
                except (KeyError, TypeError) as e:
                    logger.warning(
                        f"Skipping invalid embedding at index {idx}: {str(e)}"
                    )
                    continue

            return embeddings

        else:
            raise ValueError("Missing 'data' or 'embeddings' field in JSON data")

    def _parse_jsonl(self, content: str) -> List[EmbeddingData]:
        """
        Parse JSONL format embedding data.

        Each line should be a JSON object representing one embedding.

        Args:
            content: JSONL string content

        Returns:
            List of EmbeddingData objects
        """
        embeddings = []
        lines = content.strip().split("\n")

        for idx, line in enumerate(lines):
            line = line.strip()
            if not line:
                continue

            try:
                emb_data = json.loads(line)
                embeddings.append(EmbeddingData.from_dict(emb_data))
            except (json.JSONDecodeError, KeyError, TypeError) as e:
                logger.warning(
                    f"Skipping invalid embedding at line {idx + 1}: {str(e)}"
                )
                continue

        return embeddings

    def _parse_json_streaming(self, data: bytes) -> List[EmbeddingData]:
        """
        Parse JSON using streaming parser for large files.
        
        This method uses ijson to parse JSON incrementally, which significantly
        reduces memory usage for large embedding files. It processes embeddings
        one at a time instead of loading the entire file into memory.
        
        Args:
            data: Raw JSON data as bytes
            
        Returns:
            List of EmbeddingData objects
            
        Raises:
            ValueError: If format is invalid or ijson is not available
        """
        if not IJSON_AVAILABLE:
            raise ValueError("Streaming JSON parsing requires ijson library")
        
        embeddings = []
        
        try:
            # Create a file-like object from bytes
            file_obj = BytesIO(data)
            
            # Try to parse as Marengo 3.0 format with 'data' field
            # ijson.items() yields complete objects at the specified path
            try:
                # Check if data field is an array
                parser = ijson.items(file_obj, 'data.item')
                for emb_data in parser:
                    try:
                        embeddings.append(EmbeddingData.from_dict(emb_data))
                    except (KeyError, TypeError) as e:
                        logger.warning(f"Skipping invalid embedding: {str(e)}")
                        continue
                
                if embeddings:
                    logger.debug(
                        f"Parsed {len(embeddings)} embeddings using streaming parser "
                        f"(Marengo 3.0 array format)"
                    )
                    return embeddings
            except (ijson.JSONError, ijson.IncompleteJSONError):
                # Not an array, try single object
                pass
            
            # Reset file pointer
            file_obj.seek(0)
            
            # Try parsing data field as single object
            try:
                parser = ijson.items(file_obj, 'data')
                for emb_data in parser:
                    if isinstance(emb_data, dict):
                        try:
                            embeddings.append(EmbeddingData.from_dict(emb_data))
                        except (KeyError, TypeError) as e:
                            logger.warning(f"Skipping invalid embedding: {str(e)}")
                            continue
                
                if embeddings:
                    logger.debug(
                        f"Parsed {len(embeddings)} embeddings using streaming parser "
                        f"(Marengo 3.0 single object format)"
                    )
                    return embeddings
            except (ijson.JSONError, ijson.IncompleteJSONError):
                pass
            
            # Reset file pointer
            file_obj.seek(0)
            
            # Try legacy format with 'embeddings' field
            try:
                parser = ijson.items(file_obj, 'embeddings.item')
                for emb_data in parser:
                    try:
                        embeddings.append(EmbeddingData.from_dict(emb_data))
                    except (KeyError, TypeError) as e:
                        logger.warning(f"Skipping invalid embedding: {str(e)}")
                        continue
                
                if embeddings:
                    logger.debug(
                        f"Parsed {len(embeddings)} embeddings using streaming parser "
                        f"(legacy format)"
                    )
                    return embeddings
            except (ijson.JSONError, ijson.IncompleteJSONError):
                pass
            
            # If we got here, no valid format was found
            raise ValueError(
                "Could not parse JSON with streaming parser. "
                "Missing 'data' or 'embeddings' field."
            )
            
        except Exception as e:
            logger.error(f"Streaming JSON parsing failed: {str(e)}")
            # Fall back to standard parsing
            logger.debug("Falling back to standard JSON parsing")
            content = data.decode("utf-8")
            return self._parse_json(content)
